### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by maxjacobson**
I made a few small changes here while preparing to make a feature change and thought I'd open them in their own PR. Some additional context in the individual commits.

### CODE REVIEW

**Comment by wfleming** [comment]
Aside from the warnings, I'm in favor of this. To me, the warnings are still helpful because 1) that should be a smell indicating we should evaluate and update or eliminate dependencies and 2) we don't want to hide any warnings we could introduce in our own code in the future.

**Comment by maxjacobson** [comment]
Hm, fair enough. If we upgrade virtus from 1.0.0 to 1.0.5, all of the warnings from dependencies go away, leaving ~20 from our own code. Thoughts on doing that upgrade and resolving them now or punting and trying to tolerate the cluttered output? Here they are fwiw:

```
/Users/maxjacobson/src/codeclimate-services/lib/cc/service.rb:74: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/maxjacobson/src/codeclimate-services/lib/cc/service.rb:83: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/maxjacobson/src/codeclimate-services/test/github_pull_requests_test.rb:159: warning: assigned but unused variable - response
/Users/maxjacobson/src/codeclimate-services/test/github_pull_requests_test.rb:172: warning: assigned but unused variable - response
/Users/maxjacobson/src/codeclimate-services/test/gitlab_merge_requests_test.rb:157: warning: assigned but unused variable - response
/Users/maxjacobson/src/codeclimate-services/test/gitlab_merge_requests_test.rb:173: warning: assigned but unused variable - response
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:79: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:93: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:107: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/maxjacobson/src/codeclimate-services/test/service_test.rb:37: warning: shadowing outer local variable - response
/Users/maxjacobson/src/codeclimate-services/test/service_test.rb:52: warning: shadowing outer local variable - response
/Users/maxjacobson/src/codeclimate-services/lib/cc/services/slack.rb:75: warning: instance variable @response not initialized
/Users/maxjacobson/src/codeclimate-services/lib/cc/services/slack.rb:75: warning: instance variable @response not initialized
/Users/maxjacobson/src/codeclimate-services/lib/cc/services/slack.rb:75: warning: instance variable @response not initialized
/Users/maxjacobson/src/codeclimate-services/lib/cc/services/slack.rb:75: warning: instance variable @response not initialized
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:140: warning: instance variable @fake_error not initialized
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:140: warning: instance variable @fake_error not initialized
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:140: warning: instance variable @fake_error not initialized
/Users/maxjacobson/src/codeclimate-services/test/invocation_test.rb:140: warning: instance variable @fake_error not initialized
```

**Comment by wfleming** [comment]
That's a very small upgrade, so I hope it would be safe. I say go for it in a separate PR.

**Comment by maxjacobson** [comment]
👍 -- removed the warning disabling, will plan to merge this one and open another PR to address the warnings

**Pull request merged**
